# Generated by Django 3.0 on 2019-12-08 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=13, help_text='Latitude coordinate for squirrel sighting point', max_digits=16, validators=[django.core.validators.MaxValueValidator(41), django.core.validators.MinValueValidator(40)])),
                ('Longitude', models.DecimalField(decimal_places=13, help_text='Longitude coordinate for squirrel sighting point', max_digits=16, validators=[django.core.validators.MaxValueValidator(-73), django.core.validators.MinValueValidator(-74)])),
                ('Unique_Squirrel_ID', models.CharField(help_text='Identification tag for each squirrel sightings. The tag is comprised of "Hectare ID" + "Shift" + "Date" + "Hectare Squirrel Number.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('\\d{1,2}[A-I]-[PA]M-\\d{4}-\\d{2}', message='Please enter the right ID.')])),
                ('Shift', models.CharField(choices=[('PM', 'P.M.'), ('AM', 'A.M.')], help_text='Value is either "AM" or "PM," to communicate whether or not the sighting session occurred in the morning or late afternoon.', max_length=2)),
                ('Date', models.DateField(help_text='Concatenation of the sighting session day,month and year.(formate: YYYY-MM-DD)')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'adult'), ('Juvenile', 'juvenile')], help_text='Value is either "adult" or "juvenile".', max_length=10)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'gray'), ('Cinnamon', 'cinnamon'), ('Black', 'black')], help_text='Value is either "gray," "cinnamon" or "black".', max_length=10)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'ground plane'), ('Above Ground', 'above ground')], help_text='Value is either "ground plane" or "above ground." Sighters were instructed to indicate the location of where the squirrel was when first sighted.', max_length=20)),
                ('Specific_Location', models.CharField(blank=True, help_text='Sighters occasionally added commentary on the squirrel location. These notes are provided here.', max_length=100)),
                ('Running', models.BooleanField(help_text='Squirrel was seen running.')),
                ('Chasing', models.BooleanField(help_text='Squirrel was seen chasing another squirrel.')),
                ('Climbing', models.BooleanField(help_text='Squirrel was seen climbing a tree or other environmental landmark.')),
                ('Eating', models.BooleanField(help_text='Squirrel was seen eating.')),
                ('Foraging', models.BooleanField(help_text='Squirrel was seen foraging for food.')),
                ('Other_Activities', models.CharField(blank=True, max_length=100)),
                ('Kuks', models.BooleanField(help_text='Squirrel was heard kukking, a chirpy vocal communication used for a variety of reasons.')),
                ('Quaas', models.BooleanField(help_text='Squirrel was heard quaaing, an elongated vocal communication which can indicate the presence of a ground predator such as a dog.')),
                ('Moans', models.BooleanField(help_text='Squirrel was heard moaning, a high-pitched vocal communication which can indicate the presence of an air predator such as a hawk.')),
                ('Tail_flags', models.BooleanField(help_text="Squirrel was seen flagging its tail. Flagging is a whipping motion used to exaggerate squirrel's size and confuse rivals or predators. Looks as if the squirrel is scribbling with tail into the air.")),
                ('Tail_twitches', models.BooleanField(help_text='Squirrel was seen twitching its tail. Looks like a wave running through the tail, like a breakdancer doing the arm wave. Often used to communicate interest, curiosity.')),
                ('Approaches', models.BooleanField(help_text='Squirrel was seen approaching human, seeking food.')),
                ('Indifferent', models.BooleanField(help_text='Squirrel was indifferent to human presence.')),
                ('Runs_from', models.BooleanField(help_text='Squirrel was seen running from humans, seeing them as a threat.')),
            ],
        ),
    ]
